build-windows:
  runs-on: windows-latest
  defaults:
    run:
      shell: pwsh # Usa PowerShell explicitamente
      working-directory: .
  
  steps:
  - name: Checkout código
    uses: actions/checkout@v4
    
  - name: Configurar Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
  
  - name: Instalar dependências
    run: |
      python -m pip install --upgrade pip
      pip install pyinstaller
      if (Test-Path "requirements.txt") { pip install -r requirements.txt }
  
  - name: Build do executável Windows
    run: |
      pyinstaller --onefile `
        --add-data "updater.py:." `
        --add-data "launcher.py:." `
        --add-data "assets/background.png:assets" `
        --add-data "assets/banner.png:assets" `
        --add-data "assets/icon.ico:assets" `
        --add-data "assets/icon.png:assets" `
        --add-data "assets/modification_icon.png:assets" `
        --add-data "assets/settings_icon.png:assets" `
        --add-data "assets/discord_icon.png:assets" `
        --icon="assets/icon.png" `
        --clean `
        --windowed `
        --name="CanaryClient" `
        main.py
