name: Build Windows Executable

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (exist requirements.txt) pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name CanaryClient main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/CanaryClient.exe
