name: Build Windows Executable

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name CanaryClient main.py ^
        --hidden-import PyQt6.QtGui ^
        --hidden-import PyQt6.QtWidgets ^
        --hidden-import PyQt6.QtCore ^
        --add-data "C:\path\to\Lib\site-packages\PyQt6\Qt6\plugins;PyQt6\Qt6\plugins"

    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/CanaryClient.exe
